<html>
<body bgcolor="yellow">
<center>
<h1>Jenkins Docker Swarm Integration</h1>
</center>
<h2>1. Java Source Code is generated by using Maven Archetype:generate command.</h2>
<h2>2. Source Code is Pushed to Github</h2>
<h2>3. Jenkins Pulls the Code from Github</h2>
<h2>4. Jenkins Builds the Code using Maven Build Tool and generates Artifact</h2>
<h2>5. Jenkins Builds the Docker Images using Dockerfile specified along with source code</h2>
<h2>6. Jenkins Pushes the Docker Image to Docker Hub(Public Repository)</h2>
<h2>7. Jenkins Runs the Docker Image in Docker Swarm Master Server by connecting through SSH</h2>
<h2>8. Application is Accessible through any machine in Docker Swarm Cluster</h2>
</body>
</html>
